.PHONY: all clean
all: hello.c fahrenheit_celsius.c fahrenheit_celsius_float_version
	gcc -o build/hello.exe hello.c
	gcc -o build/fahrenheit_celsius.exe fahrenheit_celsius.c
	gcc -o build/fahrenheit_celsius_float_version.exe fahrenheit_celsius_float_version.c

clean: 
	rm -f build/*